# Site settings
title: "Statistics Mathematics, Machine-Learning and IA blog"
author: "Martín Alcubierre"
description: "This is a blog about software, some mathematics and python libraris use for Mathematics and Machine-Learning problems"
keywords: "Software Engineering, Mathematics, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "Engineer in Barcelona, working in BI and Cloud service projects. Very interested in the new wave of Machine-Learning and IA applications"
colophon: "2017 by Martín Alcubierre Arenillas.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."
disqus_shortname: https-m-alcu-github-io

baseurl: ""
url: "https://m-alcu.github.io/"

twitter_username: alcubierre
github_username: m-alcu
linkedin_username: martinalcubierre
facebook_username: m.alcubierre
google-analytics: UA-110961235-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
